IF OBJECT_ID('dbo.Tags', 'U') IS NOT NULL
  DROP TABLE dbo.Tags;
GO

CREATE TABLE Tags (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name NVARCHAR(100) NOT NULL UNIQUE,
    ImageUrl NVARCHAR(500) NULL,
    CreateDate DATETIME NOT NULL DEFAULT GETDATE()
);
GO